apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: nuodb-operator
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: ashukl
  displayName: "NuoDB Opeartor"
  publisher: "NuoDB Inc."
