kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nuodb-ce-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: nuodb-test1
roleRef:
  kind: ClusterRole
  name: nuodb-ce-operator
  apiGroup: rbac.authorization.k8s.io
