# Example deployment of a  NuoDB CE Cluster with reduced SM and TE cpu
# requirement so it can run in a small OpenShift cluster with limited
# CPU cores.

apiVersion: nuodb.com/v1alpha1
kind: Nuodb
metadata:
  name: nuodb
spec:
  replicaCount: 1
  smCpu: 250m
  teCpu: 250m
  adminStorageClass: local-disk
