 # Kubernetes Role Based Access Control for the NuoDB Operator

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nuodb-operator
rules:
- apiGroups:
  - nuodb.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-nuodb-operator
subjects:
- kind: ServiceAccount
  name: default
roleRef:
#  kind: Role
#  name: nuodb-operator
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
